DROP TABLE IF EXISTS `bom_snapshot`;

DROP TABLE IF EXISTS `bomnode_snapshot`;

DROP TABLE IF EXISTS `imexport_task`;

CREATE TABLE `bom_snapshot` (
  `creation_date` datetime DEFAULT current_timestamp(),
  `creation_user_id`  VARCHAR(64) NULL  DEFAULT NULL ,
  `creation_username`  VARCHAR(128) NULL  DEFAULT NULL ,
  `last_update` datetime DEFAULT current_timestamp(),
  `last_update_user_id`  VARCHAR(64) NULL  DEFAULT NULL ,
  `last_update_username`  VARCHAR(128) NULL  DEFAULT NULL ,
  `owner_id`  VARCHAR(64) NULL  DEFAULT NULL ,
  `owner_name`  VARCHAR(128) NULL  DEFAULT NULL ,
  `object_name`  VARCHAR(128) NULL  DEFAULT NULL ,
  `object_desc`  VARCHAR(1024) NULL  DEFAULT NULL ,
  `object_type`  VARCHAR(64) NULL  DEFAULT NULL ,
  `life_cycle_state` varchar(64) DEFAULT 'Working',
  `state_change_date` datetime DEFAULT current_timestamp(),
  `remark`  VARCHAR(512) NULL  DEFAULT NULL ,
  `secret_level`  VARCHAR(128) NULL  DEFAULT NULL ,
  `secret_term`  VARCHAR(128) NULL  DEFAULT NULL ,
  `tenant_id`  VARCHAR(64) NULL  DEFAULT NULL ,
  `uid`  VARCHAR(64) NOT NULL ,
  `del_flag` bit(1) NOT NULL DEFAULT b'0',
  `bom_view`  VARCHAR(128) NULL  DEFAULT NULL ,
  `rev_uid`  VARCHAR(64) NULL  DEFAULT NULL ,
  `rev_object_type`  VARCHAR(64) NULL  DEFAULT NULL ,
  `revision_id`  VARCHAR(64) NULL  DEFAULT NULL ,
  `item_id`  VARCHAR(64) NULL  DEFAULT NULL ,
  `item_uid`  VARCHAR(64) NULL  DEFAULT NULL ,
 PRIMARY KEY (`uid`) USING BTREE
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE `bomnode_snapshot` (
   `creation_date` datetime DEFAULT current_timestamp(),
  `creation_user_id` varchar(64) DEFAULT NULL,
  `creation_username` varchar(128) DEFAULT NULL,
  `last_update` datetime DEFAULT current_timestamp(),
  `last_update_user_id` varchar(64) DEFAULT NULL,
  `last_update_username` varchar(128) DEFAULT NULL,
  `owner_id` varchar(64) DEFAULT NULL,
  `owner_name` varchar(128) DEFAULT NULL,
  `object_name` varchar(128) DEFAULT NULL,
  `object_desc` varchar(1024) DEFAULT NULL,
  `object_type` varchar(64) DEFAULT NULL,
  `life_cycle_state` varchar(64) DEFAULT 'Working',
  `state_change_date` datetime DEFAULT current_timestamp(),
  `remark` varchar(512) DEFAULT NULL,
  `secret_level` varchar(128) DEFAULT NULL,
  `secret_term` varchar(128) DEFAULT NULL,
  `tenant_id` varchar(64) DEFAULT NULL,
  `uid` varchar(64) NOT NULL,
  `del_flag` bit(1) NOT NULL DEFAULT b'0',
  `bom_view` varchar(64) DEFAULT NULL,
  `parent_item` varchar(64) DEFAULT NULL,
  `parent_item_type` varchar(64) DEFAULT NULL,
  `parent_item_rev` varchar(64) DEFAULT '0',
  `child_item` varchar(64) DEFAULT NULL,
  `child_item_type` varchar(64) DEFAULT NULL,
  `child_item_revision` varchar(64) DEFAULT NULL,
  `child_item_type_revision` varchar(64) DEFAULT NULL,
  `quantity` double DEFAULT 1,
  `found_no` int(11) DEFAULT NULL,
  `node_type` varchar(64) DEFAULT NULL,
  `sequence_no` int(11) DEFAULT NULL,
  `bom_relation_view` varchar(64) DEFAULT NULL,
  `parent_item_rev_id` varchar(64) DEFAULT '0',
  `is_take_item` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否集件',
  `child_item_rev_id` varchar(64) DEFAULT '0',
  `tag_no` varchar(64) DEFAULT NULL COMMENT '位号',
  `manual_task_time` int(11) DEFAULT 0 COMMENT '手动工时',
  `task_time` int(11) DEFAULT 0 COMMENT '总工时',
  `snapshot_id`  VARCHAR(64) NULL  DEFAULT NULL ,
  `his_bom_id`  VARCHAR(64) NULL  DEFAULT NULL ,
 PRIMARY KEY (`uid`) USING BTREE
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT 'bom行快照';
CREATE TABLE `imexport_task` (
  `creation_date` datetime DEFAULT current_timestamp(),
  `creation_user_id`  VARCHAR(64) NULL  DEFAULT NULL ,
  `creation_username`  VARCHAR(128) NULL  DEFAULT NULL ,
  `last_update` datetime DEFAULT current_timestamp(),
  `last_update_user_id`  VARCHAR(64) NULL  DEFAULT NULL ,
  `last_update_username`  VARCHAR(128) NULL  DEFAULT NULL ,
  `owner_id`  VARCHAR(64) NULL  DEFAULT NULL ,
  `owner_name`  VARCHAR(128) NULL  DEFAULT NULL ,
  `object_name`  VARCHAR(128) NULL  DEFAULT NULL ,
  `object_desc`  VARCHAR(1024) NULL  DEFAULT NULL ,
  `object_type`  VARCHAR(64) NULL  DEFAULT NULL ,
  `life_cycle_state` varchar(64) DEFAULT 'Working',
  `state_change_date` datetime DEFAULT current_timestamp(),
  `remark`  VARCHAR(512) NULL  DEFAULT NULL ,
  `secret_level`  VARCHAR(128) NULL  DEFAULT NULL ,
  `secret_term`  VARCHAR(128) NULL  DEFAULT NULL ,
  `tenant_id`  VARCHAR(64) NULL  DEFAULT NULL ,
  `uid`  VARCHAR(64) NOT NULL ,
  `del_flag` bit(1) NOT NULL DEFAULT b'0',
  `operation_type`  VARCHAR(32) NULL  DEFAULT NULL ,
  `app_code`  VARCHAR(64) NULL  DEFAULT NULL ,
  `operation_object_type`  VARCHAR(128) NULL  DEFAULT NULL ,
  `task_name`  VARCHAR(255) NULL  DEFAULT NULL ,
  `file_name`  VARCHAR(255) NULL  DEFAULT NULL ,
  `start_date`  DATE NULL  DEFAULT NULL ,
  `end_date`  DATE NULL  DEFAULT NULL ,
  `operation_status`  VARCHAR(32) NULL  DEFAULT NULL ,
  `export_url`  VARCHAR(255) NULL  DEFAULT NULL ,
  `error_log`  text  DEFAULT NULL ,
 PRIMARY KEY (`uid`) USING BTREE
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT '导入导出';

ALTER TABLE `lzdigit_rd_624`.`bom_snapshot`
ADD UNIQUE INDEX `index_revId`(`rev_uid`, `rev_object_type`) USING BTREE;