DROP TABLE IF EXISTS `bomnode`;
CREATE TABLE `bomnode` (
                           creation_date          datetime             DEFAULT NOW(),
                           `creation_user_id`  VARCHAR(64) NULL  DEFAULT NULL ,
                           `creation_username`  VARCHAR(128) NULL  DEFAULT NULL ,
                           last_update          datetime             DEFAULT NOW(),
                           `last_update_user_id`  VARCHAR(64) NULL  DEFAULT NULL ,
                           `last_update_username`  VARCHAR(128) NULL  DEFAULT NULL ,
                           `owner_id`  VARCHAR(64) NULL  DEFAULT NULL ,
                           `owner_name`  VARCHAR(128) NULL  DEFAULT NULL ,
                           `object_name`  VARCHAR(128) NULL  DEFAULT NULL ,
                           `object_desc`  VARCHAR(1024) NULL  DEFAULT NULL ,
                           `object_type`  VARCHAR(64) NULL  DEFAULT NULL ,
                           `life_cycle_state` varchar(64) DEFAULT 'Working',
                           state_change_date          datetime             DEFAULT NOW(),
                           `remark`  VARCHAR(512) NULL  DEFAULT NULL ,
                           `secret_level`  VARCHAR(128) NULL  DEFAULT NULL ,
                           `secret_term`  VARCHAR(128) NULL  DEFAULT NULL ,
                           `tenant_id`  VARCHAR(64) NULL  DEFAULT NULL ,
                           `uid`  VARCHAR(64) NOT NULL ,
                           del_flag             BIT(1)      NOT NULL DEFAULT b'0',
                           `bom_view`  VARCHAR(64) NULL  DEFAULT NULL ,
                           `parent_item`  VARCHAR(64) NULL  DEFAULT NULL ,
                           `parent_item_type`  VARCHAR(64) NULL  DEFAULT NULL ,
                           `parent_item_rev`  VARCHAR(64) NULL  DEFAULT NULL ,
                           `child_item`  VARCHAR(64) NULL  DEFAULT NULL ,
                           `child_item_type`  VARCHAR(64) NULL  DEFAULT NULL ,
                           `child_item_revision`  VARCHAR(64) NULL  DEFAULT NULL ,
                           `child_item_type_revision`  VARCHAR(64) NULL  DEFAULT NULL ,
                           `quantity`  DOUBLE NULL  DEFAULT NULL ,
                           `found_no`  INTEGER NULL  DEFAULT NULL ,
                           `node_type`  VARCHAR(64) NULL  DEFAULT NULL ,
                           `sequence`  VARCHAR(64) NULL  DEFAULT NULL ,
                           PRIMARY KEY (`uid`) USING BTREE
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
DROP TABLE IF EXISTS `gte4cnstr_process_revision`;
CREATE TABLE `gte4cnstr_process_revision` (
                                              `gte4product_no`  VARCHAR(64) NULL  DEFAULT NULL ,
                                              `gte4product_name`  VARCHAR(128) NULL  DEFAULT NULL ,
                                              `gte4part_name`  VARCHAR(128) NULL  DEFAULT NULL ,
                                              `gte4part_no`  VARCHAR(64) NULL  DEFAULT NULL ,
                                              `gte4type`  VARCHAR(128) NULL  DEFAULT NULL ,
                                              `gte4phase`  VARCHAR(64) NULL  DEFAULT NULL ,
                                              `gte4time`  INTEGER NULL  DEFAULT NULL ,
                                              `gte4order`  VARCHAR(64) NULL  DEFAULT NULL ,
                                              `gte4work_order`  VARCHAR(64) NULL  DEFAULT NULL ,
                                              `gte4unit_no`  VARCHAR(64) NULL  DEFAULT NULL ,
                                              `gte4bn`  VARCHAR(64) NULL  DEFAULT NULL ,
                                              `gte4process_code`  VARCHAR(64) NULL  DEFAULT NULL ,
                                              `gte4process_id`  VARCHAR(64) NULL  DEFAULT NULL ,
                                              `gte4process_rev`  VARCHAR(64) NULL  DEFAULT NULL ,
                                              creation_date          datetime             DEFAULT NOW(),
                                              `creation_user_id`  VARCHAR(64) NULL  DEFAULT NULL ,
                                              `creation_username`  VARCHAR(128) NULL  DEFAULT NULL ,
                                              last_update          datetime             DEFAULT NOW(),
                                              `last_update_user_id`  VARCHAR(64) NULL  DEFAULT NULL ,
                                              `last_update_username`  VARCHAR(128) NULL  DEFAULT NULL ,
                                              `owner_id`  VARCHAR(64) NULL  DEFAULT NULL ,
                                              `owner_name`  VARCHAR(128) NULL  DEFAULT NULL ,
                                              `object_name`  VARCHAR(128) NULL  DEFAULT NULL ,
                                              `object_desc`  VARCHAR(1024) NULL  DEFAULT NULL ,
                                              `object_type`  VARCHAR(64) NULL  DEFAULT NULL ,
                                              `life_cycle_state` varchar(64) DEFAULT 'Working',
                                              state_change_date          datetime             DEFAULT NOW(),
                                              `remark`  VARCHAR(512) NULL  DEFAULT NULL ,
                                              `secret_level`  VARCHAR(128) NULL  DEFAULT NULL ,
                                              `secret_term`  VARCHAR(128) NULL  DEFAULT NULL ,
                                              `tenant_id`  VARCHAR(64) NULL  DEFAULT NULL ,
                                              `item_id`  VARCHAR(64) NULL  DEFAULT NULL ,
                                              `revision_id`  VARCHAR(64) NULL  DEFAULT NULL ,
                                              `uom`  VARCHAR(64) NULL  DEFAULT NULL ,
                                              `sequence`  VARCHAR(64) NULL  DEFAULT NULL ,
                                              `item_rev_state`  VARCHAR(64) NULL  DEFAULT NULL ,
                                              `active`  BIT(1) NULL  DEFAULT NULL ,
                                              `part_no`  VARCHAR(64) NULL  DEFAULT NULL ,
                                              `uid`  VARCHAR(64) NOT NULL ,
                                              del_flag             BIT(1)      NOT NULL DEFAULT b'0',
                                              PRIMARY KEY (`uid`) USING BTREE
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
DROP TABLE IF EXISTS `gte4cnstr_process`;
CREATE TABLE `gte4cnstr_process` (
                                     `item_id`  VARCHAR(64) NULL  DEFAULT NULL ,
                                     creation_date          datetime             DEFAULT NOW(),
                                     `creation_user_id`  VARCHAR(64) NULL  DEFAULT NULL ,
                                     `creation_username`  VARCHAR(128) NULL  DEFAULT NULL ,
                                     last_update          datetime             DEFAULT NOW(),
                                     `last_update_user_id`  VARCHAR(64) NULL  DEFAULT NULL ,
                                     `last_update_username`  VARCHAR(128) NULL  DEFAULT NULL ,
                                     `owner_id`  VARCHAR(64) NULL  DEFAULT NULL ,
                                     `owner_name`  VARCHAR(128) NULL  DEFAULT NULL ,
                                     `object_name`  VARCHAR(128) NULL  DEFAULT NULL ,
                                     `object_desc`  VARCHAR(1024) NULL  DEFAULT NULL ,
                                     `object_type`  VARCHAR(64) NULL  DEFAULT NULL ,
                                     `life_cycle_state` varchar(64) DEFAULT 'Working',
                                     state_change_date          datetime             DEFAULT NOW(),
                                     `remark`  VARCHAR(512) NULL  DEFAULT NULL ,
                                     `secret_level`  VARCHAR(128) NULL  DEFAULT NULL ,
                                     `secret_term`  VARCHAR(128) NULL  DEFAULT NULL ,
                                     `tenant_id`  VARCHAR(64) NULL  DEFAULT NULL ,
                                     `uid`  VARCHAR(64) NOT NULL ,
                                     del_flag             BIT(1)      NOT NULL DEFAULT b'0',
                                     PRIMARY KEY (`uid`) USING BTREE
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
DROP TABLE IF EXISTS `gte4mfg_operation_revision`;
CREATE TABLE `gte4mfg_operation_revision` (
                                              `gte4coop_org`  VARCHAR(128) NULL  DEFAULT NULL ,
                                              creation_date          datetime             DEFAULT NOW(),
                                              `creation_user_id`  VARCHAR(64) NULL  DEFAULT NULL ,
                                              `creation_username`  VARCHAR(128) NULL  DEFAULT NULL ,
                                              last_update          datetime             DEFAULT NOW(),
                                              `last_update_user_id`  VARCHAR(64) NULL  DEFAULT NULL ,
                                              `last_update_username`  VARCHAR(128) NULL  DEFAULT NULL ,
                                              `owner_id`  VARCHAR(64) NULL  DEFAULT NULL ,
                                              `owner_name`  VARCHAR(128) NULL  DEFAULT NULL ,
                                              `object_name`  VARCHAR(128) NULL  DEFAULT NULL ,
                                              `object_desc`  VARCHAR(1024) NULL  DEFAULT NULL ,
                                              `object_type`  VARCHAR(64) NULL  DEFAULT NULL ,
                                              `life_cycle_state` varchar(64) DEFAULT 'Working',
                                              state_change_date          datetime             DEFAULT NOW(),
                                              `remark`  VARCHAR(512) NULL  DEFAULT NULL ,
                                              `secret_level`  VARCHAR(128) NULL  DEFAULT NULL ,
                                              `secret_term`  VARCHAR(128) NULL  DEFAULT NULL ,
                                              `tenant_id`  VARCHAR(64) NULL  DEFAULT NULL ,
                                              `item_id`  VARCHAR(64) NULL  DEFAULT NULL ,
                                              `revision_id`  VARCHAR(64) NULL  DEFAULT NULL ,
                                              `uom`  VARCHAR(64) NULL  DEFAULT NULL ,
                                              `sequence`  VARCHAR(64) NULL  DEFAULT NULL ,
                                              `item_rev_state`  VARCHAR(64) NULL  DEFAULT NULL ,
                                              `active`  BIT(1) NULL  DEFAULT NULL ,
                                              `part_no`  VARCHAR(64) NULL  DEFAULT NULL ,
                                              `uid`  VARCHAR(64) NOT NULL ,
                                              del_flag             BIT(1)      NOT NULL DEFAULT b'0',
                                              `op_type`  VARCHAR(64) NULL  DEFAULT NULL ,
                                              `is_key`  BIT(1) NULL  DEFAULT NULL ,
                                              PRIMARY KEY (`uid`) USING BTREE
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
DROP TABLE IF EXISTS `gte4mfg_operation`;
CREATE TABLE `gte4mfg_operation` (
                                     `item_id`  VARCHAR(64) NULL  DEFAULT NULL ,
                                     creation_date          datetime             DEFAULT NOW(),
                                     `creation_user_id`  VARCHAR(64) NULL  DEFAULT NULL ,
                                     `creation_username`  VARCHAR(128) NULL  DEFAULT NULL ,
                                     last_update          datetime             DEFAULT NOW(),
                                     `last_update_user_id`  VARCHAR(64) NULL  DEFAULT NULL ,
                                     `last_update_username`  VARCHAR(128) NULL  DEFAULT NULL ,
                                     `owner_id`  VARCHAR(64) NULL  DEFAULT NULL ,
                                     `owner_name`  VARCHAR(128) NULL  DEFAULT NULL ,
                                     `object_name`  VARCHAR(128) NULL  DEFAULT NULL ,
                                     `object_desc`  VARCHAR(1024) NULL  DEFAULT NULL ,
                                     `object_type`  VARCHAR(64) NULL  DEFAULT NULL ,
                                     `life_cycle_state` varchar(64) DEFAULT 'Working',
                                     state_change_date          datetime             DEFAULT NOW(),
                                     `remark`  VARCHAR(512) NULL  DEFAULT NULL ,
                                     `secret_level`  VARCHAR(128) NULL  DEFAULT NULL ,
                                     `secret_term`  VARCHAR(128) NULL  DEFAULT NULL ,
                                     `tenant_id`  VARCHAR(64) NULL  DEFAULT NULL ,
                                     `uid`  VARCHAR(64) NOT NULL ,
                                     del_flag             BIT(1)      NOT NULL DEFAULT b'0',
                                     PRIMARY KEY (`uid`) USING BTREE
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
DROP TABLE IF EXISTS `gte4mfg_process_revision`;
CREATE TABLE `gte4mfg_process_revision` (
                                            `gte4product_no`  VARCHAR(64) NULL  DEFAULT NULL ,
                                            `gte4product_name`  VARCHAR(128) NULL  DEFAULT NULL ,
                                            `gte4part_name`  VARCHAR(128) NULL  DEFAULT NULL ,
                                            `gte4part_no`  VARCHAR(64) NULL  DEFAULT NULL ,
                                            `gte4type`  VARCHAR(128) NULL  DEFAULT NULL ,
                                            `gte4phase`  VARCHAR(64) NULL  DEFAULT NULL ,
                                            creation_date          datetime             DEFAULT NOW(),
                                            `creation_user_id`  VARCHAR(64) NULL  DEFAULT NULL ,
                                            `creation_username`  VARCHAR(128) NULL  DEFAULT NULL ,
                                            last_update          datetime             DEFAULT NOW(),
                                            `last_update_user_id`  VARCHAR(64) NULL  DEFAULT NULL ,
                                            `last_update_username`  VARCHAR(128) NULL  DEFAULT NULL ,
                                            `owner_id`  VARCHAR(64) NULL  DEFAULT NULL ,
                                            `owner_name`  VARCHAR(128) NULL  DEFAULT NULL ,
                                            `object_name`  VARCHAR(128) NULL  DEFAULT NULL ,
                                            `object_desc`  VARCHAR(1024) NULL  DEFAULT NULL ,
                                            `object_type`  VARCHAR(64) NULL  DEFAULT NULL ,
                                            `life_cycle_state` varchar(64) DEFAULT 'Working',
                                            state_change_date          datetime             DEFAULT NOW(),
                                            `remark`  VARCHAR(512) NULL  DEFAULT NULL ,
                                            `secret_level`  VARCHAR(128) NULL  DEFAULT NULL ,
                                            `secret_term`  VARCHAR(128) NULL  DEFAULT NULL ,
                                            `tenant_id`  VARCHAR(64) NULL  DEFAULT NULL ,
                                            `item_id`  VARCHAR(64) NULL  DEFAULT NULL ,
                                            `revision_id`  VARCHAR(64) NULL  DEFAULT NULL ,
                                            `uom`  VARCHAR(64) NULL  DEFAULT NULL ,
                                            `sequence`  VARCHAR(64) NULL  DEFAULT NULL ,
                                            `item_rev_state`  VARCHAR(64) NULL  DEFAULT NULL ,
                                            `active`  BIT(1) NULL  DEFAULT NULL ,
                                            `part_no`  VARCHAR(64) NULL  DEFAULT NULL ,
                                            `uid`  VARCHAR(64) NOT NULL ,
                                            `owner_group_name`  VARCHAR(128) NULL  DEFAULT NULL ,
                                            del_flag             BIT(1)      NOT NULL DEFAULT b'0',
                                            PRIMARY KEY (`uid`) USING BTREE
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
DROP TABLE IF EXISTS `gte4mfg_process`;
CREATE TABLE `gte4mfg_process` (
                                   `item_id`  VARCHAR(64) NULL  DEFAULT NULL ,
                                   creation_date          datetime             DEFAULT NOW(),
                                   `creation_user_id`  VARCHAR(64) NULL  DEFAULT NULL ,
                                   `creation_username`  VARCHAR(128) NULL  DEFAULT NULL ,
                                   last_update          datetime             DEFAULT NOW(),
                                   `last_update_user_id`  VARCHAR(64) NULL  DEFAULT NULL ,
                                   `last_update_username`  VARCHAR(128) NULL  DEFAULT NULL ,
                                   `owner_id`  VARCHAR(64) NULL  DEFAULT NULL ,
                                   `owner_name`  VARCHAR(128) NULL  DEFAULT NULL ,
                                   `object_name`  VARCHAR(128) NULL  DEFAULT NULL ,
                                   `object_desc`  VARCHAR(1024) NULL  DEFAULT NULL ,
                                   `object_type`  VARCHAR(64) NULL  DEFAULT NULL ,
                                   `life_cycle_state`  VARCHAR(64) DEFAULT 'Working',
                                   state_change_date          datetime             DEFAULT NOW(),
                                   `remark`  VARCHAR(512) NULL  DEFAULT NULL ,
                                   `secret_level`  VARCHAR(128) NULL  DEFAULT NULL ,
                                   `secret_term`  VARCHAR(128) NULL  DEFAULT NULL ,
                                   `tenant_id`  VARCHAR(64) NULL  DEFAULT NULL ,
                                   `uid`  VARCHAR(64) NOT NULL ,
                                   del_flag             BIT(1)      NOT NULL DEFAULT b'0',
                                   PRIMARY KEY (`uid`) USING BTREE
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
DROP TABLE IF EXISTS `gte4mfg_step`;
CREATE TABLE `gte4mfg_step` (
                                `gte4coop_org`  VARCHAR(128) NULL  DEFAULT NULL ,
                                creation_date          datetime             DEFAULT NOW(),
                                `creation_user_id`  VARCHAR(64) NULL  DEFAULT NULL ,
                                `creation_username`  VARCHAR(128) NULL  DEFAULT NULL ,
                                last_update          datetime             DEFAULT NOW(),
                                `last_update_user_id`  VARCHAR(64) NULL  DEFAULT NULL ,
                                `last_update_username`  VARCHAR(128) NULL  DEFAULT NULL ,
                                `owner_id`  VARCHAR(64) NULL  DEFAULT NULL ,
                                `owner_name`  VARCHAR(128) NULL  DEFAULT NULL ,
                                `object_name`  VARCHAR(128) NULL  DEFAULT NULL ,
                                `object_desc`  VARCHAR(1024) NULL  DEFAULT NULL ,
                                `object_type`  VARCHAR(64) NULL  DEFAULT NULL ,
                                `life_cycle_state` varchar(64) DEFAULT 'Working',
                                state_change_date          datetime             DEFAULT NOW(),
                                `remark`  VARCHAR(512) NULL  DEFAULT NULL ,
                                `secret_level`  VARCHAR(128) NULL  DEFAULT NULL ,
                                `secret_term`  VARCHAR(128) NULL  DEFAULT NULL ,
                                `tenant_id`  VARCHAR(64) NULL  DEFAULT NULL ,
                                `uid`  VARCHAR(64) NOT NULL ,
                                del_flag             BIT(1)      NOT NULL DEFAULT b'0',
                                `gte4_type`  VARCHAR(64) NULL  DEFAULT NULL ,
                                `step_content`  VARCHAR(1024) NULL  DEFAULT NULL ,
                                PRIMARY KEY (`uid`) USING BTREE
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
DROP TABLE IF EXISTS `item_revision`;
CREATE TABLE `item_revision` (
                                 creation_date          datetime             DEFAULT NOW(),
                                 `creation_user_id`  VARCHAR(64) NULL  DEFAULT NULL ,
                                 `creation_username`  VARCHAR(128) NULL  DEFAULT NULL ,
                                 last_update          datetime             DEFAULT NOW(),
                                 `last_update_user_id`  VARCHAR(64) NULL  DEFAULT NULL ,
                                 `last_update_username`  VARCHAR(128) NULL  DEFAULT NULL ,
                                 `owner_id`  VARCHAR(64) NULL  DEFAULT NULL ,
                                 `owner_name`  VARCHAR(128) NULL  DEFAULT NULL ,
                                 `object_name`  VARCHAR(128) NULL  DEFAULT NULL ,
                                 `object_desc`  VARCHAR(1024) NULL  DEFAULT NULL ,
                                 `object_type`  VARCHAR(64) NULL  DEFAULT NULL ,
                                 `life_cycle_state` varchar(64) DEFAULT 'Working',
                                 state_change_date          datetime             DEFAULT NOW(),
                                 `remark`  VARCHAR(512) NULL  DEFAULT NULL ,
                                 `secret_level`  VARCHAR(128) NULL  DEFAULT NULL ,
                                 `secret_term`  VARCHAR(128) NULL  DEFAULT NULL ,
                                 `tenant_id`  VARCHAR(64) NULL  DEFAULT NULL ,
                                 `item_id`  VARCHAR(64) NULL  DEFAULT NULL ,
                                 `revision_id`  VARCHAR(64) NULL  DEFAULT NULL ,
                                 `uom`  VARCHAR(64) NULL  DEFAULT NULL ,
                                 `sequence`  VARCHAR(64) NULL  DEFAULT NULL ,
                                 `item_rev_state`  VARCHAR(64) NULL  DEFAULT NULL ,
                                 `active`  BIT(1) NULL  DEFAULT NULL ,
                                 `part_no`  VARCHAR(64) NULL  DEFAULT NULL ,
                                 `uid`  VARCHAR(64) NOT NULL ,
                                 del_flag             BIT(1)      NOT NULL DEFAULT b'0',
                                 PRIMARY KEY (`uid`) USING BTREE
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
DROP TABLE IF EXISTS `item`;
CREATE TABLE `item` (
                        `item_id`  VARCHAR(64) NULL  DEFAULT NULL ,
                        creation_date          datetime             DEFAULT NOW(),
                        `creation_user_id`  VARCHAR(64) NULL  DEFAULT NULL ,
                        `creation_username`  VARCHAR(128) NULL  DEFAULT NULL ,
                        last_update          datetime             DEFAULT NOW(),
                        `last_update_user_id`  VARCHAR(64) NULL  DEFAULT NULL ,
                        `last_update_username`  VARCHAR(128) NULL  DEFAULT NULL ,
                        `owner_id`  VARCHAR(64) NULL  DEFAULT NULL ,
                        `owner_name`  VARCHAR(128) NULL  DEFAULT NULL ,
                        `object_name`  VARCHAR(128) NULL  DEFAULT NULL ,
                        `object_desc`  VARCHAR(1024) NULL  DEFAULT NULL ,
                        `object_type`  VARCHAR(64) NULL  DEFAULT NULL ,
                        `life_cycle_state` varchar(64) DEFAULT 'Working',
                        state_change_date          datetime             DEFAULT NOW(),
                        `remark`  VARCHAR(512) NULL  DEFAULT NULL ,
                        `secret_level`  VARCHAR(128) NULL  DEFAULT NULL ,
                        `secret_term`  VARCHAR(128) NULL  DEFAULT NULL ,
                        `tenant_id`  VARCHAR(64) NULL  DEFAULT NULL ,
                        `part_no`  VARCHAR(64) NULL  DEFAULT NULL ,
                        `uid`  VARCHAR(64) NOT NULL ,
                        del_flag             BIT(1)      NOT NULL DEFAULT b'0',
                        PRIMARY KEY (`uid`) USING BTREE
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
