DROP TABLE IF EXISTS `gte4mfg_line_pr_revision`;

DROP TABLE IF EXISTS `gte4mfg_line_pr`;

DROP TABLE IF EXISTS `gte4mfg_operation_revision`;

DROP TABLE IF EXISTS `gte4mfg_operation`;

DROP TABLE IF EXISTS `gte4mfg_plant_pr_revision`;

DROP TABLE IF EXISTS `gte4mfg_plant_pr`;

DROP TABLE IF EXISTS `gte4mfg_station_pr_revision`;

DROP TABLE IF EXISTS `gte4mfg_station_pr`;

DROP TABLE IF EXISTS `gte4mfg_step`;

DROP TABLE IF EXISTS `gte4plant_revision`;

DROP TABLE IF EXISTS `gte4plant`;

DROP TABLE IF EXISTS `gte4station_revision`;

DROP TABLE IF EXISTS `gte4station`;

DROP TABLE IF EXISTS `gte4workline_revision`;

DROP TABLE IF EXISTS `gte4workline`;

DROP TABLE IF EXISTS `gte4plantrl`;

DROP TABLE IF EXISTS `gte4worklinerl`;

CREATE TABLE `gte4mfg_line_pr_revision` (
  `creation_date` datetime DEFAULT current_timestamp(),
  `creation_user_id`  VARCHAR(64) NULL  DEFAULT NULL ,
  `creation_username`  VARCHAR(128) NULL  DEFAULT NULL ,
  `last_update` datetime DEFAULT current_timestamp(),
  `last_update_user_id`  VARCHAR(64) NULL  DEFAULT NULL ,
  `last_update_username`  VARCHAR(128) NULL  DEFAULT NULL ,
  `owner_id`  VARCHAR(64) NULL  DEFAULT NULL ,
  `owner_name`  VARCHAR(128) NULL  DEFAULT NULL ,
  `object_name`  VARCHAR(128) NULL  DEFAULT NULL ,
  `object_desc`  VARCHAR(1024) NULL  DEFAULT NULL ,
  `object_type`  VARCHAR(64) NULL  DEFAULT NULL ,
  `life_cycle_state` varchar(64) DEFAULT 'Working',
  `state_change_date` datetime DEFAULT current_timestamp(),
  `remark`  VARCHAR(512) NULL  DEFAULT NULL ,
  `secret_level`  VARCHAR(128) NULL  DEFAULT NULL ,
  `secret_term`  VARCHAR(128) NULL  DEFAULT NULL ,
  `tenant_id`  VARCHAR(64) NULL  DEFAULT NULL ,
  `item_id`  VARCHAR(64) NULL  DEFAULT NULL ,
  `revision_id`  VARCHAR(64) NULL  DEFAULT NULL ,
  `uom`  VARCHAR(64) NULL  DEFAULT NULL ,
  `sequence`  VARCHAR(64) NULL  DEFAULT NULL ,
  `item_rev_state`  VARCHAR(64) NULL  DEFAULT NULL ,
  `active`  BIT(1) NULL  DEFAULT NULL ,
  `uid`  VARCHAR(64) NOT NULL ,
  `del_flag` bit(1) NOT NULL DEFAULT b'0',
  `gte4the_direction`  VARCHAR(128) NULL  DEFAULT NULL ,
  `gte4process_classification`  VARCHAR(128) NULL  DEFAULT NULL ,
  `gte4panel_model`  VARCHAR(128) NULL  DEFAULT NULL ,
 PRIMARY KEY (`uid`) USING BTREE  
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE `gte4mfg_line_pr` (
  `item_id`  VARCHAR(64) NULL  DEFAULT NULL ,
  `creation_date` datetime DEFAULT current_timestamp(),
  `creation_user_id`  VARCHAR(64) NULL  DEFAULT NULL ,
  `creation_username`  VARCHAR(128) NULL  DEFAULT NULL ,
  `last_update` datetime DEFAULT current_timestamp(),
  `last_update_user_id`  VARCHAR(64) NULL  DEFAULT NULL ,
  `last_update_username`  VARCHAR(128) NULL  DEFAULT NULL ,
  `owner_id`  VARCHAR(64) NULL  DEFAULT NULL ,
  `owner_name`  VARCHAR(128) NULL  DEFAULT NULL ,
  `object_name`  VARCHAR(128) NULL  DEFAULT NULL ,
  `object_desc`  VARCHAR(1024) NULL  DEFAULT NULL ,
  `object_type`  VARCHAR(64) NULL  DEFAULT NULL ,
  `life_cycle_state` varchar(64) DEFAULT 'Working',
  `state_change_date` datetime DEFAULT current_timestamp(),
  `remark`  VARCHAR(512) NULL  DEFAULT NULL ,
  `secret_level`  VARCHAR(128) NULL  DEFAULT NULL ,
  `secret_term`  VARCHAR(128) NULL  DEFAULT NULL ,
  `tenant_id`  VARCHAR(64) NULL  DEFAULT NULL ,
  `uid`  VARCHAR(64) NOT NULL ,
  `del_flag` bit(1) NOT NULL DEFAULT b'0',
 PRIMARY KEY (`uid`) USING BTREE  
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE `gte4mfg_operation_revision` (
  `creation_date` datetime DEFAULT current_timestamp(),
  `creation_user_id`  VARCHAR(64) NULL  DEFAULT NULL ,
  `creation_username`  VARCHAR(128) NULL  DEFAULT NULL ,
  `last_update` datetime DEFAULT current_timestamp(),
  `last_update_user_id`  VARCHAR(64) NULL  DEFAULT NULL ,
  `last_update_username`  VARCHAR(128) NULL  DEFAULT NULL ,
  `owner_id`  VARCHAR(64) NULL  DEFAULT NULL ,
  `owner_name`  VARCHAR(128) NULL  DEFAULT NULL ,
  `object_name`  VARCHAR(128) NULL  DEFAULT NULL ,
  `object_desc`  VARCHAR(1024) NULL  DEFAULT NULL ,
  `object_type`  VARCHAR(64) NULL  DEFAULT NULL ,
  `life_cycle_state` varchar(64) DEFAULT 'Working',
  `state_change_date` datetime DEFAULT current_timestamp(),
  `remark`  VARCHAR(512) NULL  DEFAULT NULL ,
  `secret_level`  VARCHAR(128) NULL  DEFAULT NULL ,
  `secret_term`  VARCHAR(128) NULL  DEFAULT NULL ,
  `tenant_id`  VARCHAR(64) NULL  DEFAULT NULL ,
  `item_id`  VARCHAR(64) NULL  DEFAULT NULL ,
  `revision_id`  VARCHAR(64) NULL  DEFAULT NULL ,
  `uom`  VARCHAR(64) NULL  DEFAULT NULL ,
  `sequence`  VARCHAR(64) NULL  DEFAULT NULL ,
  `item_rev_state`  VARCHAR(64) NULL  DEFAULT NULL ,
  `active`  BIT(1) NULL  DEFAULT NULL ,
  `uid`  VARCHAR(64) NOT NULL ,
  `del_flag` bit(1) NOT NULL DEFAULT b'0',
  `op_type`  VARCHAR(64) NULL  DEFAULT NULL ,
  `is_key`  BIT(1) NULL  DEFAULT NULL ,
  `gte4coop_org`  VARCHAR(128) NULL  DEFAULT NULL ,
  `gte4action_description`  VARCHAR(128) NULL  DEFAULT NULL ,
  `gte4examine_points`  longtext DEFAULT NULL,
  `gte4process_req`  VARCHAR(255) NULL  DEFAULT NULL ,
  `gte4sampling_ratio`  DOUBLE NULL  DEFAULT NULL ,
  `gte4test_points`  VARCHAR(255) NULL  DEFAULT NULL ,
  `gte4task_time`  INTEGER NULL  DEFAULT NULL ,
 PRIMARY KEY (`uid`) USING BTREE  
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE `gte4mfg_operation` (
  `item_id`  VARCHAR(64) NULL  DEFAULT NULL ,
  `creation_date` datetime DEFAULT current_timestamp(),
  `creation_user_id`  VARCHAR(64) NULL  DEFAULT NULL ,
  `creation_username`  VARCHAR(128) NULL  DEFAULT NULL ,
  `last_update` datetime DEFAULT current_timestamp(),
  `last_update_user_id`  VARCHAR(64) NULL  DEFAULT NULL ,
  `last_update_username`  VARCHAR(128) NULL  DEFAULT NULL ,
  `owner_id`  VARCHAR(64) NULL  DEFAULT NULL ,
  `owner_name`  VARCHAR(128) NULL  DEFAULT NULL ,
  `object_name`  VARCHAR(128) NULL  DEFAULT NULL ,
  `object_desc`  VARCHAR(1024) NULL  DEFAULT NULL ,
  `object_type`  VARCHAR(64) NULL  DEFAULT NULL ,
  `life_cycle_state` varchar(64) DEFAULT 'Working',
  `state_change_date` datetime DEFAULT current_timestamp(),
  `remark`  VARCHAR(512) NULL  DEFAULT NULL ,
  `secret_level`  VARCHAR(128) NULL  DEFAULT NULL ,
  `secret_term`  VARCHAR(128) NULL  DEFAULT NULL ,
  `tenant_id`  VARCHAR(64) NULL  DEFAULT NULL ,
  `uid`  VARCHAR(64) NOT NULL ,
  `del_flag` bit(1) NOT NULL DEFAULT b'0',
 PRIMARY KEY (`uid`) USING BTREE  
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE `gte4mfg_plant_pr_revision` (
  `creation_date` datetime DEFAULT current_timestamp(),
  `creation_user_id`  VARCHAR(64) NULL  DEFAULT NULL ,
  `creation_username`  VARCHAR(128) NULL  DEFAULT NULL ,
  `last_update` datetime DEFAULT current_timestamp(),
  `last_update_user_id`  VARCHAR(64) NULL  DEFAULT NULL ,
  `last_update_username`  VARCHAR(128) NULL  DEFAULT NULL ,
  `owner_id`  VARCHAR(64) NULL  DEFAULT NULL ,
  `owner_name`  VARCHAR(128) NULL  DEFAULT NULL ,
  `object_name`  VARCHAR(128) NULL  DEFAULT NULL ,
  `object_desc`  VARCHAR(1024) NULL  DEFAULT NULL ,
  `object_type`  VARCHAR(64) NULL  DEFAULT NULL ,
  `life_cycle_state` varchar(64) DEFAULT 'Working',
  `state_change_date` datetime DEFAULT current_timestamp(),
  `remark`  VARCHAR(512) NULL  DEFAULT NULL ,
  `secret_level`  VARCHAR(128) NULL  DEFAULT NULL ,
  `secret_term`  VARCHAR(128) NULL  DEFAULT NULL ,
  `tenant_id`  VARCHAR(64) NULL  DEFAULT NULL ,
  `item_id`  VARCHAR(64) NULL  DEFAULT NULL ,
  `revision_id`  VARCHAR(64) NULL  DEFAULT NULL ,
  `uom`  VARCHAR(64) NULL  DEFAULT NULL ,
  `sequence`  VARCHAR(64) NULL  DEFAULT NULL ,
  `item_rev_state`  VARCHAR(64) NULL  DEFAULT NULL ,
  `active`  BIT(1) NULL  DEFAULT NULL ,
  `uid`  VARCHAR(64) NOT NULL ,
  `del_flag` bit(1) NOT NULL DEFAULT b'0',
  `gte4lead_free`  BIT(1) NULL  DEFAULT NULL ,
  `gte4electrostatic_protection`  VARCHAR(64) NULL  DEFAULT NULL ,
  `gte4dust_rating`  VARCHAR(64) NULL  DEFAULT NULL ,
  `gte4pcbsize_length`  DOUBLE NULL  DEFAULT NULL ,
  `gte4pcbsize_width`  DOUBLE NULL  DEFAULT NULL ,
  `gte4pcbsize_heigth`  DOUBLE NULL  DEFAULT NULL ,
 PRIMARY KEY (`uid`) USING BTREE  
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE `gte4mfg_plant_pr` (
  `item_id`  VARCHAR(64) NULL  DEFAULT NULL ,
  `creation_date` datetime DEFAULT current_timestamp(),
  `creation_user_id`  VARCHAR(64) NULL  DEFAULT NULL ,
  `creation_username`  VARCHAR(128) NULL  DEFAULT NULL ,
  `last_update` datetime DEFAULT current_timestamp(),
  `last_update_user_id`  VARCHAR(64) NULL  DEFAULT NULL ,
  `last_update_username`  VARCHAR(128) NULL  DEFAULT NULL ,
  `owner_id`  VARCHAR(64) NULL  DEFAULT NULL ,
  `owner_name`  VARCHAR(128) NULL  DEFAULT NULL ,
  `object_name`  VARCHAR(128) NULL  DEFAULT NULL ,
  `object_desc`  VARCHAR(1024) NULL  DEFAULT NULL ,
  `object_type`  VARCHAR(64) NULL  DEFAULT NULL ,
  `life_cycle_state` varchar(64) DEFAULT 'Working',
  `state_change_date` datetime DEFAULT current_timestamp(),
  `remark`  VARCHAR(512) NULL  DEFAULT NULL ,
  `secret_level`  VARCHAR(128) NULL  DEFAULT NULL ,
  `secret_term`  VARCHAR(128) NULL  DEFAULT NULL ,
  `tenant_id`  VARCHAR(64) NULL  DEFAULT NULL ,
  `uid`  VARCHAR(64) NOT NULL ,
  `del_flag` bit(1) NOT NULL DEFAULT b'0',
 PRIMARY KEY (`uid`) USING BTREE  
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE `gte4mfg_station_pr_revision` (
  `creation_date` datetime DEFAULT current_timestamp(),
  `creation_user_id`  VARCHAR(64) NULL  DEFAULT NULL ,
  `creation_username`  VARCHAR(128) NULL  DEFAULT NULL ,
  `last_update` datetime DEFAULT current_timestamp(),
  `last_update_user_id`  VARCHAR(64) NULL  DEFAULT NULL ,
  `last_update_username`  VARCHAR(128) NULL  DEFAULT NULL ,
  `owner_id`  VARCHAR(64) NULL  DEFAULT NULL ,
  `owner_name`  VARCHAR(128) NULL  DEFAULT NULL ,
  `object_name`  VARCHAR(128) NULL  DEFAULT NULL ,
  `object_desc`  VARCHAR(1024) NULL  DEFAULT NULL ,
  `object_type`  VARCHAR(64) NULL  DEFAULT NULL ,
  `life_cycle_state` varchar(64) DEFAULT 'Working',
  `state_change_date` datetime DEFAULT current_timestamp(),
  `remark`  VARCHAR(512) NULL  DEFAULT NULL ,
  `secret_level`  VARCHAR(128) NULL  DEFAULT NULL ,
  `secret_term`  VARCHAR(128) NULL  DEFAULT NULL ,
  `tenant_id`  VARCHAR(64) NULL  DEFAULT NULL ,
  `item_id`  VARCHAR(64) NULL  DEFAULT NULL ,
  `revision_id`  VARCHAR(64) NULL  DEFAULT NULL ,
  `uom`  VARCHAR(64) NULL  DEFAULT NULL ,
  `sequence`  VARCHAR(64) NULL  DEFAULT NULL ,
  `item_rev_state`  VARCHAR(64) NULL  DEFAULT NULL ,
  `active`  BIT(1) NULL  DEFAULT NULL ,
  `uid`  VARCHAR(64) NOT NULL ,
  `del_flag` bit(1) NOT NULL DEFAULT b'0',
  `gte4change_record`  VARCHAR(1024) NULL  DEFAULT NULL ,
  `gte4special_characteristics`  VARCHAR(128) NULL  DEFAULT NULL ,
  `gte4exception_cautions`  VARCHAR(1024) NULL  DEFAULT NULL ,
  `gte4key_info_program`  longtext DEFAULT NULL,
  `gte4key_process`  BIT(1) NULL  DEFAULT NULL ,
 PRIMARY KEY (`uid`) USING BTREE  
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE `gte4mfg_station_pr` (
  `item_id`  VARCHAR(64) NULL  DEFAULT NULL ,
  `creation_date` datetime DEFAULT current_timestamp(),
  `creation_user_id`  VARCHAR(64) NULL  DEFAULT NULL ,
  `creation_username`  VARCHAR(128) NULL  DEFAULT NULL ,
  `last_update` datetime DEFAULT current_timestamp(),
  `last_update_user_id`  VARCHAR(64) NULL  DEFAULT NULL ,
  `last_update_username`  VARCHAR(128) NULL  DEFAULT NULL ,
  `owner_id`  VARCHAR(64) NULL  DEFAULT NULL ,
  `owner_name`  VARCHAR(128) NULL  DEFAULT NULL ,
  `object_name`  VARCHAR(128) NULL  DEFAULT NULL ,
  `object_desc`  VARCHAR(1024) NULL  DEFAULT NULL ,
  `object_type`  VARCHAR(64) NULL  DEFAULT NULL ,
  `life_cycle_state` varchar(64) DEFAULT 'Working',
  `state_change_date` datetime DEFAULT current_timestamp(),
  `remark`  VARCHAR(512) NULL  DEFAULT NULL ,
  `secret_level`  VARCHAR(128) NULL  DEFAULT NULL ,
  `secret_term`  VARCHAR(128) NULL  DEFAULT NULL ,
  `tenant_id`  VARCHAR(64) NULL  DEFAULT NULL ,
  `uid`  VARCHAR(64) NOT NULL ,
  `del_flag` bit(1) NOT NULL DEFAULT b'0',
 PRIMARY KEY (`uid`) USING BTREE  
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE `gte4mfg_step` (
  `creation_date` datetime DEFAULT current_timestamp(),
  `creation_user_id`  VARCHAR(64) NULL  DEFAULT NULL ,
  `creation_username`  VARCHAR(128) NULL  DEFAULT NULL ,
  `last_update` datetime DEFAULT current_timestamp(),
  `last_update_user_id`  VARCHAR(64) NULL  DEFAULT NULL ,
  `last_update_username`  VARCHAR(128) NULL  DEFAULT NULL ,
  `owner_id`  VARCHAR(64) NULL  DEFAULT NULL ,
  `owner_name`  VARCHAR(128) NULL  DEFAULT NULL ,
  `object_name`  VARCHAR(128) NULL  DEFAULT NULL ,
  `object_desc`  VARCHAR(1024) NULL  DEFAULT NULL ,
  `object_type`  VARCHAR(64) NULL  DEFAULT NULL ,
  `life_cycle_state` varchar(64) DEFAULT 'Working',
  `state_change_date` datetime DEFAULT current_timestamp(),
  `remark`  VARCHAR(512) NULL  DEFAULT NULL ,
  `secret_level`  VARCHAR(128) NULL  DEFAULT NULL ,
  `secret_term`  VARCHAR(128) NULL  DEFAULT NULL ,
  `tenant_id`  VARCHAR(64) NULL  DEFAULT NULL ,
  `item_id`  VARCHAR(64) NULL  DEFAULT NULL ,
  `uid`  VARCHAR(64) NOT NULL ,
  `del_flag` bit(1) NOT NULL DEFAULT b'0',
  `gte4coop_org` varchar(128) DEFAULT NULL,
  `gte4_type` varchar(64) DEFAULT NULL,
  `step_content` longtext DEFAULT NULL,
  `is_execute` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否已执行',
  `gte4task_time`  INTEGER NULL  DEFAULT NULL ,
  `gte4frequency`  DOUBLE NULL  DEFAULT NULL ,
 PRIMARY KEY (`uid`) USING BTREE  
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE `gte4plant_revision` (
  `creation_date` datetime DEFAULT current_timestamp(),
  `creation_user_id`  VARCHAR(64) NULL  DEFAULT NULL ,
  `creation_username`  VARCHAR(128) NULL  DEFAULT NULL ,
  `last_update` datetime DEFAULT current_timestamp(),
  `last_update_user_id`  VARCHAR(64) NULL  DEFAULT NULL ,
  `last_update_username`  VARCHAR(128) NULL  DEFAULT NULL ,
  `owner_id`  VARCHAR(64) NULL  DEFAULT NULL ,
  `owner_name`  VARCHAR(128) NULL  DEFAULT NULL ,
  `object_name`  VARCHAR(128) NULL  DEFAULT NULL ,
  `object_desc`  VARCHAR(1024) NULL  DEFAULT NULL ,
  `object_type`  VARCHAR(64) NULL  DEFAULT NULL ,
  `life_cycle_state` varchar(64) DEFAULT 'Working',
  `state_change_date` datetime DEFAULT current_timestamp(),
  `remark`  VARCHAR(512) NULL  DEFAULT NULL ,
  `secret_level`  VARCHAR(128) NULL  DEFAULT NULL ,
  `secret_term`  VARCHAR(128) NULL  DEFAULT NULL ,
  `tenant_id`  VARCHAR(64) NULL  DEFAULT NULL ,
  `item_id`  VARCHAR(64) NULL  DEFAULT NULL ,
  `revision_id`  VARCHAR(64) NULL  DEFAULT NULL ,
  `uom`  VARCHAR(64) NULL  DEFAULT NULL ,
  `sequence`  VARCHAR(64) NULL  DEFAULT NULL ,
  `item_rev_state`  VARCHAR(64) NULL  DEFAULT NULL ,
  `active`  BIT(1) NULL  DEFAULT NULL ,
  `uid`  VARCHAR(64) NOT NULL ,
  `del_flag` bit(1) NOT NULL DEFAULT b'0',
  `gte4order_no`  VARCHAR(128) NULL  DEFAULT NULL ,
  `gte4plant_type`  VARCHAR(128) NULL  DEFAULT NULL ,
  `gte4address`  VARCHAR(256) NULL  DEFAULT NULL ,
  `gte4plant_nature`  VARCHAR(128) NULL  DEFAULT NULL ,
  `gte4mesorg_code`  VARCHAR(64) NULL  DEFAULT NULL ,
 PRIMARY KEY (`uid`) USING BTREE  
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE `gte4plant` (
  `item_id`  VARCHAR(64) NULL  DEFAULT NULL ,
  `creation_date` datetime DEFAULT current_timestamp(),
  `creation_user_id`  VARCHAR(64) NULL  DEFAULT NULL ,
  `creation_username`  VARCHAR(128) NULL  DEFAULT NULL ,
  `last_update` datetime DEFAULT current_timestamp(),
  `last_update_user_id`  VARCHAR(64) NULL  DEFAULT NULL ,
  `last_update_username`  VARCHAR(128) NULL  DEFAULT NULL ,
  `owner_id`  VARCHAR(64) NULL  DEFAULT NULL ,
  `owner_name`  VARCHAR(128) NULL  DEFAULT NULL ,
  `object_name`  VARCHAR(128) NULL  DEFAULT NULL ,
  `object_desc`  VARCHAR(1024) NULL  DEFAULT NULL ,
  `object_type`  VARCHAR(64) NULL  DEFAULT NULL ,
  `life_cycle_state` varchar(64) DEFAULT 'Working',
  `state_change_date` datetime DEFAULT current_timestamp(),
  `remark`  VARCHAR(512) NULL  DEFAULT NULL ,
  `secret_level`  VARCHAR(128) NULL  DEFAULT NULL ,
  `secret_term`  VARCHAR(128) NULL  DEFAULT NULL ,
  `tenant_id`  VARCHAR(64) NULL  DEFAULT NULL ,
  `uid`  VARCHAR(64) NOT NULL ,
  `del_flag` bit(1) NOT NULL DEFAULT b'0',
 PRIMARY KEY (`uid`) USING BTREE  
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE `gte4station_revision` (
  `creation_date` datetime DEFAULT current_timestamp(),
  `creation_user_id`  VARCHAR(64) NULL  DEFAULT NULL ,
  `creation_username`  VARCHAR(128) NULL  DEFAULT NULL ,
  `last_update` datetime DEFAULT current_timestamp(),
  `last_update_user_id`  VARCHAR(64) NULL  DEFAULT NULL ,
  `last_update_username`  VARCHAR(128) NULL  DEFAULT NULL ,
  `owner_id`  VARCHAR(64) NULL  DEFAULT NULL ,
  `owner_name`  VARCHAR(128) NULL  DEFAULT NULL ,
  `object_name`  VARCHAR(128) NULL  DEFAULT NULL ,
  `object_desc`  VARCHAR(1024) NULL  DEFAULT NULL ,
  `object_type`  VARCHAR(64) NULL  DEFAULT NULL ,
  `life_cycle_state` varchar(64) DEFAULT 'Working',
  `state_change_date` datetime DEFAULT current_timestamp(),
  `remark`  VARCHAR(512) NULL  DEFAULT NULL ,
  `secret_level`  VARCHAR(128) NULL  DEFAULT NULL ,
  `secret_term`  VARCHAR(128) NULL  DEFAULT NULL ,
  `tenant_id`  VARCHAR(64) NULL  DEFAULT NULL ,
  `item_id`  VARCHAR(64) NULL  DEFAULT NULL ,
  `revision_id`  VARCHAR(64) NULL  DEFAULT NULL ,
  `uom`  VARCHAR(64) NULL  DEFAULT NULL ,
  `sequence`  VARCHAR(64) NULL  DEFAULT NULL ,
  `item_rev_state`  VARCHAR(64) NULL  DEFAULT NULL ,
  `active`  BIT(1) NULL  DEFAULT NULL ,
  `uid`  VARCHAR(64) NOT NULL ,
  `del_flag` bit(1) NOT NULL DEFAULT b'0',
  `gte4order_no`  VARCHAR(128) NULL  DEFAULT NULL ,
  `gte4station_type`  VARCHAR(128) NULL  DEFAULT NULL ,
  `gte4length_of_station`  DOUBLE NULL  DEFAULT NULL ,
  `gte4esdreq`  VARCHAR(128) NULL  DEFAULT NULL ,
  `gte4clean_req`  VARCHAR(128) NULL  DEFAULT NULL ,
 PRIMARY KEY (`uid`) USING BTREE  
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE `gte4station` (
  `item_id`  VARCHAR(64) NULL  DEFAULT NULL ,
  `creation_date` datetime DEFAULT current_timestamp(),
  `creation_user_id`  VARCHAR(64) NULL  DEFAULT NULL ,
  `creation_username`  VARCHAR(128) NULL  DEFAULT NULL ,
  `last_update` datetime DEFAULT current_timestamp(),
  `last_update_user_id`  VARCHAR(64) NULL  DEFAULT NULL ,
  `last_update_username`  VARCHAR(128) NULL  DEFAULT NULL ,
  `owner_id`  VARCHAR(64) NULL  DEFAULT NULL ,
  `owner_name`  VARCHAR(128) NULL  DEFAULT NULL ,
  `object_name`  VARCHAR(128) NULL  DEFAULT NULL ,
  `object_desc`  VARCHAR(1024) NULL  DEFAULT NULL ,
  `object_type`  VARCHAR(64) NULL  DEFAULT NULL ,
  `life_cycle_state` varchar(64) DEFAULT 'Working',
  `state_change_date` datetime DEFAULT current_timestamp(),
  `remark`  VARCHAR(512) NULL  DEFAULT NULL ,
  `secret_level`  VARCHAR(128) NULL  DEFAULT NULL ,
  `secret_term`  VARCHAR(128) NULL  DEFAULT NULL ,
  `tenant_id`  VARCHAR(64) NULL  DEFAULT NULL ,
  `uid`  VARCHAR(64) NOT NULL ,
  `del_flag` bit(1) NOT NULL DEFAULT b'0',
 PRIMARY KEY (`uid`) USING BTREE  
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE `gte4workline_revision` (
  `creation_date` datetime DEFAULT current_timestamp(),
  `creation_user_id`  VARCHAR(64) NULL  DEFAULT NULL ,
  `creation_username`  VARCHAR(128) NULL  DEFAULT NULL ,
  `last_update` datetime DEFAULT current_timestamp(),
  `last_update_user_id`  VARCHAR(64) NULL  DEFAULT NULL ,
  `last_update_username`  VARCHAR(128) NULL  DEFAULT NULL ,
  `owner_id`  VARCHAR(64) NULL  DEFAULT NULL ,
  `owner_name`  VARCHAR(128) NULL  DEFAULT NULL ,
  `object_name`  VARCHAR(128) NULL  DEFAULT NULL ,
  `object_desc`  VARCHAR(1024) NULL  DEFAULT NULL ,
  `object_type`  VARCHAR(64) NULL  DEFAULT NULL ,
  `life_cycle_state` varchar(64) DEFAULT 'Working',
  `state_change_date` datetime DEFAULT current_timestamp(),
  `remark`  VARCHAR(512) NULL  DEFAULT NULL ,
  `secret_level`  VARCHAR(128) NULL  DEFAULT NULL ,
  `secret_term`  VARCHAR(128) NULL  DEFAULT NULL ,
  `tenant_id`  VARCHAR(64) NULL  DEFAULT NULL ,
  `item_id`  VARCHAR(64) NULL  DEFAULT NULL ,
  `revision_id`  VARCHAR(64) NULL  DEFAULT NULL ,
  `uom`  VARCHAR(64) NULL  DEFAULT NULL ,
  `sequence`  VARCHAR(64) NULL  DEFAULT NULL ,
  `item_rev_state`  VARCHAR(64) NULL  DEFAULT NULL ,
  `active`  BIT(1) NULL  DEFAULT NULL ,
  `uid`  VARCHAR(64) NOT NULL ,
  `del_flag` bit(1) NOT NULL DEFAULT b'0',
  `gte4order_no`  VARCHAR(128) NULL  DEFAULT NULL ,
  `gte4workshop`  VARCHAR(128) NULL  DEFAULT NULL ,
  `gte4asset_num`  VARCHAR(128) NULL  DEFAULT NULL ,
  `gte4workarea`  VARCHAR(128) NULL  DEFAULT NULL ,
  `gte4department_name`  VARCHAR(128) NULL  DEFAULT NULL ,
  `gte4line_capacity`  VARCHAR(128) NULL  DEFAULT NULL ,
 PRIMARY KEY (`uid`) USING BTREE  
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE `gte4workline` (
  `item_id`  VARCHAR(64) NULL  DEFAULT NULL ,
  `creation_date` datetime DEFAULT current_timestamp(),
  `creation_user_id`  VARCHAR(64) NULL  DEFAULT NULL ,
  `creation_username`  VARCHAR(128) NULL  DEFAULT NULL ,
  `last_update` datetime DEFAULT current_timestamp(),
  `last_update_user_id`  VARCHAR(64) NULL  DEFAULT NULL ,
  `last_update_username`  VARCHAR(128) NULL  DEFAULT NULL ,
  `owner_id`  VARCHAR(64) NULL  DEFAULT NULL ,
  `owner_name`  VARCHAR(128) NULL  DEFAULT NULL ,
  `object_name`  VARCHAR(128) NULL  DEFAULT NULL ,
  `object_desc`  VARCHAR(1024) NULL  DEFAULT NULL ,
  `object_type`  VARCHAR(64) NULL  DEFAULT NULL ,
  `life_cycle_state` varchar(64) DEFAULT 'Working',
  `state_change_date` datetime DEFAULT current_timestamp(),
  `remark`  VARCHAR(512) NULL  DEFAULT NULL ,
  `secret_level`  VARCHAR(128) NULL  DEFAULT NULL ,
  `secret_term`  VARCHAR(128) NULL  DEFAULT NULL ,
  `tenant_id`  VARCHAR(64) NULL  DEFAULT NULL ,
  `uid`  VARCHAR(64) NOT NULL ,
  `del_flag` bit(1) NOT NULL DEFAULT b'0',
 PRIMARY KEY (`uid`) USING BTREE  
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


CREATE TABLE `gte4plantrl` (
  `relation_type`  VARCHAR(64) NULL  DEFAULT NULL ,
  `left_object`  VARCHAR(64) NULL  DEFAULT NULL ,
  `left_object_type`  VARCHAR(64) NULL  DEFAULT NULL ,
  `right_object`  VARCHAR(64) NULL  DEFAULT NULL ,
  `right_object_type`  VARCHAR(64) NULL  DEFAULT NULL ,
  `creation_date` datetime DEFAULT current_timestamp(),
  `creation_user_id`  VARCHAR(64) NULL  DEFAULT NULL ,
  `creation_username`  VARCHAR(128) NULL  DEFAULT NULL ,
  `last_update` datetime DEFAULT current_timestamp(),
  `last_update_user_id`  VARCHAR(64) NULL  DEFAULT NULL ,
  `last_update_username`  VARCHAR(128) NULL  DEFAULT NULL ,
  `owner_id`  VARCHAR(64) NULL  DEFAULT NULL ,
  `owner_name`  VARCHAR(128) NULL  DEFAULT NULL ,
  `object_name`  VARCHAR(128) NULL  DEFAULT NULL ,
  `object_desc`  VARCHAR(1024) NULL  DEFAULT NULL ,
  `object_type`  VARCHAR(64) NULL  DEFAULT NULL ,
  `life_cycle_state` varchar(64) DEFAULT 'Working',
  `state_change_date` datetime DEFAULT current_timestamp(),
  `remark`  VARCHAR(512) NULL  DEFAULT NULL ,
  `secret_level`  VARCHAR(128) NULL  DEFAULT NULL ,
  `secret_term`  VARCHAR(128) NULL  DEFAULT NULL ,
  `tenant_id`  VARCHAR(64) NULL  DEFAULT NULL ,
  `uid`  VARCHAR(64) NOT NULL ,
  `del_flag` bit(1) NOT NULL DEFAULT b'0',
 PRIMARY KEY (`uid`) USING BTREE
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT '工厂工艺与工厂的关系';
CREATE TABLE `gte4worklinerl` (
  `relation_type`  VARCHAR(64) NULL  DEFAULT NULL ,
  `left_object`  VARCHAR(64) NULL  DEFAULT NULL ,
  `left_object_type`  VARCHAR(64) NULL  DEFAULT NULL ,
  `right_object`  VARCHAR(64) NULL  DEFAULT NULL ,
  `right_object_type`  VARCHAR(64) NULL  DEFAULT NULL ,
  `creation_date` datetime DEFAULT current_timestamp(),
  `creation_user_id`  VARCHAR(64) NULL  DEFAULT NULL ,
  `creation_username`  VARCHAR(128) NULL  DEFAULT NULL ,
  `last_update` datetime DEFAULT current_timestamp(),
  `last_update_user_id`  VARCHAR(64) NULL  DEFAULT NULL ,
  `last_update_username`  VARCHAR(128) NULL  DEFAULT NULL ,
  `owner_id`  VARCHAR(64) NULL  DEFAULT NULL ,
  `owner_name`  VARCHAR(128) NULL  DEFAULT NULL ,
  `object_name`  VARCHAR(128) NULL  DEFAULT NULL ,
  `object_desc`  VARCHAR(1024) NULL  DEFAULT NULL ,
  `object_type`  VARCHAR(64) NULL  DEFAULT NULL ,
  `life_cycle_state` varchar(64) DEFAULT 'Working',
  `state_change_date` datetime DEFAULT current_timestamp(),
  `remark`  VARCHAR(512) NULL  DEFAULT NULL ,
  `secret_level`  VARCHAR(128) NULL  DEFAULT NULL ,
  `secret_term`  VARCHAR(128) NULL  DEFAULT NULL ,
  `tenant_id`  VARCHAR(64) NULL  DEFAULT NULL ,
  `uid`  VARCHAR(64) NOT NULL ,
  `del_flag` bit(1) NOT NULL DEFAULT b'0',
 PRIMARY KEY (`uid`) USING BTREE
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT '线体工艺与线体的关系';


CREATE TABLE `video` (
  `creation_date` datetime DEFAULT current_timestamp(),
  `creation_user_id`  VARCHAR(64) NULL  DEFAULT NULL ,
  `creation_username`  VARCHAR(128) NULL  DEFAULT NULL ,
  `last_update` datetime DEFAULT current_timestamp(),
  `last_update_user_id`  VARCHAR(64) NULL  DEFAULT NULL ,
  `last_update_username`  VARCHAR(128) NULL  DEFAULT NULL ,
  `owner_id`  VARCHAR(64) NULL  DEFAULT NULL ,
  `owner_name`  VARCHAR(128) NULL  DEFAULT NULL ,
  `object_name`  VARCHAR(128) NULL  DEFAULT NULL ,
  `object_desc`  VARCHAR(1024) NULL  DEFAULT NULL ,
  `object_type`  VARCHAR(64) NULL  DEFAULT NULL ,
  `life_cycle_state` varchar(64) DEFAULT 'Working',
  `state_change_date` datetime DEFAULT current_timestamp(),
  `remark`  VARCHAR(512) NULL  DEFAULT NULL ,
  `secret_level`  VARCHAR(128) NULL  DEFAULT NULL ,
  `secret_term`  VARCHAR(128) NULL  DEFAULT NULL ,
  `tenant_id`  VARCHAR(64) NULL  DEFAULT NULL ,
  `uid`  VARCHAR(64) NOT NULL ,
  `del_flag` bit(1) NOT NULL DEFAULT b'0',
 PRIMARY KEY (`uid`) USING BTREE
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;



CREATE TABLE `gte4process` (
  `item_id` varchar(64) DEFAULT NULL,
  `creation_date` datetime DEFAULT current_timestamp(),
  `creation_user_id` varchar(64) DEFAULT NULL,
  `creation_username` varchar(128) DEFAULT NULL,
  `last_update` datetime DEFAULT current_timestamp(),
  `last_update_user_id` varchar(64) DEFAULT NULL,
  `last_update_username` varchar(128) DEFAULT NULL,
  `owner_id` varchar(64) DEFAULT NULL,
  `owner_name` varchar(128) DEFAULT NULL,
  `object_name` varchar(128) DEFAULT NULL,
  `object_desc` varchar(1024) DEFAULT NULL,
  `object_type` varchar(64) DEFAULT NULL,
  `life_cycle_state` varchar(64) DEFAULT 'Working',
  `state_change_date` datetime DEFAULT current_timestamp(),
  `remark` varchar(512) DEFAULT NULL,
  `secret_level` varchar(128) DEFAULT NULL,
  `secret_term` varchar(128) DEFAULT NULL,
  `tenant_id` varchar(64) DEFAULT NULL,
  `uid` varchar(64) NOT NULL,
  `del_flag` bit(1) DEFAULT b'0',
  PRIMARY KEY (`uid`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


CREATE TABLE `gte4process_revision` (
  `creation_date` datetime DEFAULT current_timestamp(),
  `creation_user_id` varchar(64) DEFAULT NULL,
  `creation_username` varchar(128) DEFAULT NULL,
  `last_update` datetime DEFAULT current_timestamp(),
  `last_update_user_id` varchar(64) DEFAULT NULL,
  `last_update_username` varchar(128) DEFAULT NULL,
  `owner_id` varchar(64) DEFAULT NULL,
  `owner_name` varchar(128) DEFAULT NULL,
  `object_name` varchar(128) DEFAULT NULL,
  `object_desc` varchar(1024) DEFAULT NULL,
  `object_type` varchar(64) DEFAULT NULL,
  `life_cycle_state` varchar(64) DEFAULT 'Working',
  `state_change_date` datetime DEFAULT current_timestamp(),
  `remark` varchar(512) DEFAULT NULL,
  `secret_level` varchar(128) DEFAULT NULL,
  `secret_term` varchar(128) DEFAULT NULL,
  `tenant_id` varchar(64) DEFAULT NULL,
  `item_id` varchar(64) DEFAULT NULL,
  `revision_id` varchar(64) DEFAULT NULL,
  `uom` varchar(64) DEFAULT NULL,
  `sequence` varchar(64) DEFAULT NULL,
  `item_rev_state` varchar(64) DEFAULT NULL,
  `active` bit(1) DEFAULT NULL,
  `uid` varchar(64) NOT NULL,
  `del_flag` bit(1) DEFAULT b'0',
  `gte4part_no` varchar(64) DEFAULT NULL,
  `gte4cat` varchar(64) DEFAULT NULL,
  `gte4material_trade_mark` varchar(64) DEFAULT NULL,
  `gte4mat_tech_std` varchar(128) DEFAULT NULL,
  `gte4mat_spec` varchar(128) DEFAULT NULL,
  `gte4dzn_bn` varchar(64) DEFAULT NULL,
  `gte4pdmownner` varchar(128) DEFAULT NULL,
  `gte4pdmowning_group` varchar(128) DEFAULT NULL,
  `gte4init_model` varchar(64) DEFAULT NULL,
  `gte4_phase` varchar(64) DEFAULT NULL,
  PRIMARY KEY (`uid`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;





INSERT INTO `lzdigit_rd_624`.`bomview`(`creation_date`, `creation_user_id`, `creation_username`, `last_update`, `last_update_user_id`, `last_update_username`, `owner_id`, `owner_name`, `object_name`, `object_desc`, `object_type`, `life_cycle_state`, `state_change_date`, `remark`, `secret_level`, `secret_term`, `display_name`, `uid`, `del_flag`, `is_precise`, `view_type`) VALUES ('2022-08-24 10:36:05', NULL, NULL, '2022-08-24 10:36:05', NULL, NULL, NULL, NULL, NULL, '', 'bomview', 'Working', '2022-08-24 10:36:05', NULL, NULL, NULL, NULL, '1', b'0', b'0', 'EBOM');
INSERT INTO `lzdigit_rd_624`.`bomview`(`creation_date`, `creation_user_id`, `creation_username`, `last_update`, `last_update_user_id`, `last_update_username`, `owner_id`, `owner_name`, `object_name`, `object_desc`, `object_type`, `life_cycle_state`, `state_change_date`, `remark`, `secret_level`, `secret_term`, `display_name`, `uid`, `del_flag`, `is_precise`, `view_type`) VALUES ('2022-08-24 10:36:05', NULL, NULL, '2022-08-24 10:36:05', NULL, NULL, NULL, NULL, NULL, '', 'bomview', 'Working', '2022-08-24 10:36:05', NULL, NULL, NULL, NULL, '2', b'0', b'0', 'MSGBOM');
INSERT INTO `lzdigit_rd_624`.`bomview`(`creation_date`, `creation_user_id`, `creation_username`, `last_update`, `last_update_user_id`, `last_update_username`, `owner_id`, `owner_name`, `object_name`, `object_desc`, `object_type`, `life_cycle_state`, `state_change_date`, `remark`, `secret_level`, `secret_term`, `display_name`, `uid`, `del_flag`, `is_precise`, `view_type`) VALUES ('2022-08-24 10:36:05', NULL, NULL, '2022-08-24 10:36:05', NULL, NULL, NULL, NULL, NULL, '', 'bomview', 'Working', '2022-08-24 10:36:05', NULL, NULL, NULL, NULL, '3', b'0', b'1', 'FOLLOW_MSGBOM');
INSERT INTO `lzdigit_rd_624`.`bomview`(`creation_date`, `creation_user_id`, `creation_username`, `last_update`, `last_update_user_id`, `last_update_username`, `owner_id`, `owner_name`, `object_name`, `object_desc`, `object_type`, `life_cycle_state`, `state_change_date`, `remark`, `secret_level`, `secret_term`, `display_name`, `uid`, `del_flag`, `is_precise`, `view_type`) VALUES ('2022-08-24 10:36:05', NULL, NULL, '2022-08-24 10:36:05', NULL, NULL, NULL, NULL, NULL, '', 'bomview', 'Working', '2022-08-24 10:36:05', NULL, NULL, NULL, NULL, '4', b'0', b'0', 'MIDBOM');
INSERT INTO `lzdigit_rd_624`.`bomview`(`creation_date`, `creation_user_id`, `creation_username`, `last_update`, `last_update_user_id`, `last_update_username`, `owner_id`, `owner_name`, `object_name`, `object_desc`, `object_type`, `life_cycle_state`, `state_change_date`, `remark`, `secret_level`, `secret_term`, `display_name`, `uid`, `del_flag`, `is_precise`, `view_type`) VALUES ('2022-08-24 10:36:05', NULL, NULL, '2022-08-24 10:36:05', NULL, NULL, NULL, NULL, NULL, '', 'bomview', 'Working', '2022-08-24 10:36:05', NULL, NULL, NULL, NULL, '5', b'0', b'0', 'PBOM');
INSERT INTO `lzdigit_rd_624`.`bomview`(`creation_date`, `creation_user_id`, `creation_username`, `last_update`, `last_update_user_id`, `last_update_username`, `owner_id`, `owner_name`, `object_name`, `object_desc`, `object_type`, `life_cycle_state`, `state_change_date`, `remark`, `secret_level`, `secret_term`, `display_name`, `uid`, `del_flag`, `is_precise`, `view_type`) VALUES ('2022-08-24 10:36:05', NULL, NULL, '2022-08-24 10:36:05', NULL, NULL, NULL, NULL, NULL, '', 'bomview', 'Working', '2022-08-24 10:36:05', NULL, NULL, NULL, NULL, '6', b'0', b'0', 'DOCUMENTBOM');
INSERT INTO `lzdigit_rd_624`.`bomview`(`creation_date`, `creation_user_id`, `creation_username`, `last_update`, `last_update_user_id`, `last_update_username`, `owner_id`, `owner_name`, `object_name`, `object_desc`, `object_type`, `life_cycle_state`, `state_change_date`, `remark`, `secret_level`, `secret_term`, `display_name`, `uid`, `del_flag`, `is_precise`, `view_type`) VALUES ('2022-08-24 10:36:05', NULL, NULL, '2022-08-24 10:36:05', NULL, NULL, NULL, NULL, NULL, '', 'bomview', 'Working', '2022-08-24 10:36:05', NULL, NULL, NULL, NULL, '7', b'0', b'0', 'MBOM');