CREATE TABLE `gte4mfg_cnstrrl` (
  `relation_type` varchar(64) DEFAULT NULL,
  `left_object` varchar(64) DEFAULT NULL,
  `left_object_type` varchar(64) DEFAULT NULL,
  `right_object` varchar(64) DEFAULT NULL,
  `right_object_type` varchar(64) DEFAULT NULL,
  `creation_date` datetime DEFAULT current_timestamp(),
  `creation_user_id` varchar(64) DEFAULT NULL,
  `creation_username` varchar(128) DEFAULT NULL,
  `last_update` datetime DEFAULT current_timestamp(),
  `last_update_user_id` varchar(64) DEFAULT NULL,
  `last_update_username` varchar(128) DEFAULT NULL,
  `owner_id` varchar(64) DEFAULT NULL,
  `owner_name` varchar(128) DEFAULT NULL,
  `object_name` varchar(128) DEFAULT NULL,
  `object_desc` varchar(1024) DEFAULT NULL,
  `object_type` varchar(64) DEFAULT NULL,
  `life_cycle_state` varchar(64) DEFAULT 'Working',
  `state_change_date` datetime DEFAULT current_timestamp(),
  `remark` varchar(512) DEFAULT NULL,
  `secret_level` varchar(128) DEFAULT NULL,
  `secret_term` varchar(128) DEFAULT NULL,
  `display_name` varchar(1024) DEFAULT NULL,
  `uid` varchar(64) NOT NULL,
  `del_flag` bit(1) NOT NULL DEFAULT b'0',
  PRIMARY KEY (`uid`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;